// <auto-generated />
using System;
using AwinFeedSync.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AwinFeedSync.Infrastructure.Migrations
{
    [DbContext(typeof(AwinDbContext))]
    [Migration("20260131014229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AwinFeedSync.Core.Models.Advertiser", b =>
                {
                    b.Property<int>("AdvertiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("advertiser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdvertiserId"));

                    b.Property<string>("DefaultCommissionText")
                        .HasColumnType("text")
                        .HasColumnName("default_commission_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AdvertiserId");

                    b.ToTable("advertisers", (string)null);
                });

            modelBuilder.Entity("AwinFeedSync.Core.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AdvertiserId")
                        .HasColumnType("integer")
                        .HasColumnName("advertiser_id");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<string>("AiSummaryStatus")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary_status");

                    b.Property<DateTime?>("AiSummaryUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_summary_updated_at");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_rate");

                    b.Property<string>("CommissionText")
                        .HasColumnType("text")
                        .HasColumnName("commission_text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<string>("FeedProductId")
                        .HasColumnType("text")
                        .HasColumnName("feed_product_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTime?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.Property<DateTime>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_key");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text")
                        .HasColumnName("product_url");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text")
                        .HasColumnName("subcategory");

                    b.Property<string>("TrackingUrl")
                        .HasColumnType("text")
                        .HasColumnName("tracking_url");

                    b.Property<string>("TrackingUrlSource")
                        .HasColumnType("text")
                        .HasColumnName("tracking_url_source");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("LastChangedAt");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("AdvertiserId", "ProductKey")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("AwinFeedSync.Core.Models.SyncRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RunId"));

                    b.Property<int>("AdvertisersProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("advertisers_processed");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text")
                        .HasColumnName("error_text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ProductsChanged")
                        .HasColumnType("integer")
                        .HasColumnName("products_changed");

                    b.Property<int>("ProductsSeen")
                        .HasColumnType("integer")
                        .HasColumnName("products_seen");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("RunId");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("AwinFeedSync.Core.Models.Product", b =>
                {
                    b.HasOne("AwinFeedSync.Core.Models.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertiser");
                });
#pragma warning restore 612, 618
        }
    }
}
